#!/bin/bash
#Graphics switch

#. /etc/rc.conf
#. /etc/rc.d/functions

case "$1" in

	boot)
	  stat_busy "Turning both graphics on ..."
	  echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
	  echo "DDIS" > /sys/kernel/debug/vgaswitcheroo/switch
	  stat_done
	  stat_busy "Turning off Radeon ..."
	  echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
	  echo "OFF"  > /sys/kernel/debug/vgaswitcheroo/switch
	  stat_done
	  cat /sys/kernel/debug/vgaswitcheroo/switch
	  /bin/dmesg >| /var/log/dmesg.log
	;;

	switch)
	  cat /sys/kernel/debug/vgaswitcheroo/switch
	  echo "Please choose graphics to turn ON (i for intel, r for radeon):"
          read VIDEONAME
          case "$VIDEONAME" in

                i)
                  stat_busy "Turning both graphics on ..."
                  echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
                  echo "DDIS" > /sys/kernel/debug/vgaswitcheroo/switch
                  stat_done
		  stat_busy "Turning off Radeon ..."
                  echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
                  echo "OFF"  > /sys/kernel/debug/vgaswitcheroo/switch
                  stat_done
		  cat /sys/kernel/debug/vgaswitcheroo/switch
                ;;

                r)
                  stat_busy "Turning both graphics on ..."
                  echo "DIGD" > /sys/kernel/debug/vgaswitcheroo/switch
                  echo "DDIS" > /sys/kernel/debug/vgaswitcheroo/switch
                  stat_done
                  stat_busy "Turning off Intel ..."
                  echo "DDIS" > /sys/kernel/debug/vgaswitcheroo/switch
                  echo "OFF"  > /sys/kernel/debug/vgaswitcheroo/switch
                  stat_done
		  cat /sys/kernel/debug/vgaswitcheroo/switch
                ;;

                *)
                  echo "usage: $0 switch {i|r}"
                ;;
	  esac
	;;

	check)
	  cat /sys/kernel/debug/vgaswitcheroo/switch
	;;

	*)
	  echo "usage: $0 {boot|switch|check}"
	;;
esac
